### PR TITLE
Cr/issue 204

### LINKED ISSUE #204: Pull in https://github.com/zcash/zcash/pull/4216 before next windows binary release
```
netbase.cpp: In function 'bool InterruptibleRecv(uint8_t*, size_t, int, SOCKET&)':
netbase.cpp:259:49: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'char*' [-fpermissive]
         ssize_t ret = recv(hSocket, data, len, 0); // Optimistically try the recv first
                                                 ^
In file included from compat.h:29:0,
                 from netbase.h:12,
                 from netbase.cpp:10:
/usr/share/mingw-w64/include/winsock2.h:992:34: note:   initializing argument 2 of 'int recv(SOCKET, char*, int, int)'
   WINSOCK_API_LINKAGE int WSAAPI recv(SOCKET s,char *buf,int len,int flags);
                                  ^~~~
Makefile:3111: recipe for target 'libbitcoin_common_a-netbase.o' failed
```

### PR DESCRIPTION
**Pull request by cronicc**
Fixes a Windows-specific compile bug introduced in #201.
Closes #204.

### CODE REVIEW

**Review by albertog78 — APPROVED** [review]

File: doc/man/zen-cli.1 [hunk 1]
```diff
@@ -1,9 +1,9 @@
 .\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.47.3.
-.TH ZEN-CLI "1" "October 2019" "zen-cli v2.0.19" "User Commands"
+.TH ZEN-CLI "1" "November 2019" "zen-cli v2.0.19-1" "User Commands"
```
Comment (abi87) [inline doc/man/zen-cli.1:2]: Maybe this should be February 2020? Likewise for next below

**Review by abi87 — APPROVED** [review]
Only minor question about a date in doc/man. Other than that fine to me.

File: doc/man/zen-cli.1 (hunk 1 above)
Comment (cronicc) [reply doc/man/zen-cli.1:2]: The reason for the old date is that this branch is based on the 2.0.19-1 hofix release in master. Manpages and changelogs will be regenerated once all open PRs are merged and the version numbers are changed to 2.0.20.
